version: '3.1'

services:
  grpc-server:
    image: golang:1.12
    container_name: grpc-server
    restart: always
    network_mode: "host"
    working_dir: /app/cmd/server
    command: sh -c "go build . && ./server -grpc-port=9090 -db-host=localhost:3306 -db-user=hieuvecto -db-password=123abc -db-schema=grpc"
    depends_on:
      - db
    volumes:
      - ./:/app
      - go-pkg:/go/pkg
  db:
    build: ./db-image
    container_name: db
    # restart: always
    network_mode: "host"
    environment:
      MYSQL_DATABASE: 'grpc'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'hieuvecto'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123abc'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123abc'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

# Names our volume
volumes:
  go-pkg:
  my-db: